// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDsgqzM6VLFWzZbZsBv7sbFgDG--OhiC5k',
    appId: '1:676090304791:web:d069cf64534a301c53bf52',
    messagingSenderId: '676090304791',
    projectId: 'pill-tracker-32116',
    authDomain: 'pill-tracker-32116.firebaseapp.com',
    storageBucket: 'pill-tracker-32116.appspot.com',
    measurementId: 'G-KB3NK79CCS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAn4U-6HRexKIvlyOEZc7MHhERGzAcAqMU',
    appId: '1:676090304791:android:de74585708571b0853bf52',
    messagingSenderId: '676090304791',
    projectId: 'pill-tracker-32116',
    storageBucket: 'pill-tracker-32116.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANiW-wZ1XXuIafyq9iuh-k1Mg3GgRxLBg',
    appId: '1:676090304791:ios:ece8582720a5980553bf52',
    messagingSenderId: '676090304791',
    projectId: 'pill-tracker-32116',
    storageBucket: 'pill-tracker-32116.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );
}
